### ISSUE TITLE
Facebook 24+1 policy

### ISSUE THREAD

**Issue by andrewnguyen22** [jonniechow/RogueStockBot#25]
Hey @jonniechow, I read through your code and I think I identified the issue.

No message tags on your messages will leave your `subscribers` who haven't messaged you in 24 hours not receiving a message with this error: `This message is sent outside of allowed window`

This is due to facebook's updated [24+1 policy](https://chatbotslife.com/the-facebook-messenger-rules-change-in-2020-heres-how-you-can-stay-compliant-5a2ec6ff08b8)

NOTE: Your subscribers won't see that error message, the error message will be returned in your POST request.

Hope this helps.

**Comment by jonniechow** [comment]
Ah thank you so much I did not know about this policy! Would've never thought of this

**Comment by andrewnguyen22** [comment]
No there is a work around! I'm in a meeting but I will message you

**Comment by andrewnguyen22** [comment]
Add one of these 3 tags to your message POST request works, but technically it is against their policy

https://developers.facebook.com/docs/messenger-platform/send-messages/message-tags#supported_tags

I did it in the titan bot and it works well

**Comment by jonniechow** [comment]
Ok thanks so much for the help Andrew!
