### ISSUE TITLE
Fuzzy string matching to suggest appropriate product code in response to user typo

### ISSUE THREAD

**Issue by cdkini** [jonniechow/RogueStockBot#35]
It's a very minor quality of life improvement but I was thinking we could use some kind of Levenshtein or edit distance algorithm to make suggestions when a user makes a typo. For example:

**User**: plate 6 shooter
**Bot**: INVALID
You entered: "plate 6 shooter".
Item doesn't exist.
**Did you mean "plate 6-shooter"?**

I could come up with a naive approach but I think something like https://github.com/Glench/fuzzyset.js will be far more effective. Let me know if you think it adds value to the project and if you're okay with adding a dependency. I'd be happy to make a PR

**Comment by jonniechow** [comment]
Yup I think this would be a nice feature! Your help is greatly appreciated!

**Comment by cdkini** [comment]
I'm the proud owner of a little home gym thanks to you so I'm more than happy to help out where I can!
