### ISSUE TITLE
Pre-commit hook for linting

### ISSUE THREAD

**Issue by cdkini** [jonniechow/RogueStockBot#36]
I was thinking that Prettier and/or ESLint through Husky to lint staged files could be really valuable in maintaining consistency throughout the project. I guess it depends on how long you plan on supporting the project and how much more you want to add in regards to features and products. 

I'm not too familiar with the JS ecosystem but I'll take a stab at setting this up if you'd like.

**Comment by jonniechow** [comment]
This would also be great! I know my project is very unorganized right now with pretty bad styling so it would be helpful in improving it and helping it be more readable to others as well!
